### ISSUE TITLE
Ability to migrate "to" a local::lib ?

### ISSUE THREAD

**Issue by castaway** [Grinnz/App-MigrateModules#3]
I'm trying to migrate a bunch of local::libs after an upgrade, so I was a bit surprised when this tool didnt default to "put the updated modules in the 'from' path" .. any reason why not?

**Comment by Grinnz** [comment]
As documented:

> Modules are installed to the destination Perl using cpanm. To influence the install location, activate a local::lib in your environment, or use the standard Perl and cpanm environment variables, such as "PERL_MM_OPT" in ExtUtils::MakeMaker, "PERL_MB_OPT" in Module::Build, and "PERL_CPANM_OPT" in cpanm.

There's an example documented as well:

> Migrate modules to a custom local::lib location, using /opt/perl-5.28.0 to find modules within its search paths and using /opt/perl-5.28.1 to install to /opt/project/local:

    $ env PERL_CPANM_OPT='-l /opt/project/local' perl-migrate-modules /opt/perl-5.28.0 /opt/perl-5.28.1
